In [ ]:
What is NumPy?

NumPy (Numerical Python) is a Python library used for:

Mathematical calculations
Data analysis
Machine Learning
Working with large datasets
Why NumPy?

Python lists are slower for numerical operations.

marks = [78, 85, 90, 67, 88]

NumPy arrays are optimized for speed:

import numpy as np

marks = np.array([78, 85, 90, 67, 88])

Benefits:

✅ Faster

✅ Less memory

✅ Easy calculations

🔑 Important Concepts
Create Array
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr)

Output:

[10 20 30 40 50]
Array Operations
arr = np.array([1, 2, 3, 4, 5])

print(arr + 10)
print(arr * 2)
print(arr / 2)

Output:

[11 12 13 14 15]

[ 2  4  6  8 10]

[0.5 1.  1.5 2.  2.5]
Useful Functions
arr = np.array([78, 85, 90, 67, 88])

print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))
Indexing
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])
print(arr[-1])

Output:

10
50
Slicing
arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])

Output:

[20 30 40]

In [1]:
# Q1

# Create a NumPy array containing:

# [5, 10, 15, 20, 25]

# Print the array.

import numpy as np 
arr = np.array([5,10,15,20,25])
arr

array([ 5, 10, 15, 20, 25])

In [2]:
# Q2

# Create an array:

# [100, 200, 300, 400]

# Print:

# First element
# Last element
arr = np.array([100,200,300, 400])
print(arr[0])
print(arr[-1])


100
400


In [3]:
# Q3

# Create:

arr = np.array([1, 2, 3, 4, 5])

# Add 5 to every element.
print(arr + 5)

[ 6  7  8  9 10]


In [4]:
# Q4

# Multiply every element by 3.

arr = np.array([2, 4, 6, 8])
print(arr * 3)

[ 6 12 18 24]


In [5]:
# Q5

# Divide all elements by 2.

arr = np.array([10, 20, 30, 40])
print(arr / 2)


[ 5. 10. 15. 20.]


In [6]:
# Q6

# Create:

marks = np.array([78, 85, 90, 67, 88])

# Find:

# Mean
# Maximum
# Minimum
# Sum
print(marks.mean())
print(marks.max())
print(marks.min())
print(marks.sum())

81.6
90
67
408


In [7]:
# Q7

# Create:

salary = np.array([25000, 30000, 45000, 40000, 35000])

# Find:

# Highest salary
# Lowest salary
# Average salary
# Total salary
print(salary.max())
print(salary.min())
print(salary.mean())
print(salary.sum())

45000
25000
35000.0
175000


In [8]:
# Q8

# Create:

temperature = np.array([32, 35, 30, 28, 33, 31, 34])

# Find:

# Highest temperature
# Lowest temperature
# Average temperature
print(temperature.max())
print(temperature.min())
print(temperature.mean())

35
28
31.857142857142858


In [9]:
# Q9

# Create:

expenses = np.array([500, 200, 1000, 300, 700])

# Find:

# Total expense
# Highest expense
# Lowest expense
# Average expense
print(expenses.sum())
print(expenses.max())
print(expenses.min())
print(expenses.mean())

2700
1000
200
540.0


In [15]:
# Q10

# Create:

arr = np.array([10,20,30,40,50,60,70])

# Print:

# First 3 elements
# Last 3 elements
print(arr[0:3])
print(arr[-1:-4:-1])

[10 20 30]
[70 60 50]


In [16]:
# Q11

# Create:

numbers = np.array([1,2,3,4,5])

# Calculate:

# (numbers * 2) + 10

# Expected:

# [12 14 16 18 20]

print((numbers * 2) + 10)

[12 14 16 18 20]


In [17]:
# Q12

# Create an array of 10 numbers.

# Print only even-indexed elements.
arr = np.array([1,2,3,4,5,6,7,8,9,10])

print(arr[::2])

[1 3 5 7 9]


In [19]:
# Q13

# Create:

prices = np.array([100, 250, 400, 150, 300])

# Calculate a 10% increase in all prices.

print(prices + (prices * 0.1))

[110. 275. 440. 165. 330.]


In [20]:
# Q14

# Create:

scores = np.array([45, 67, 89, 92, 76])

# Find:

# Average
# Difference between highest and lowest score
print(scores.mean())
print(scores.max() - scores.min())

73.8
47


In [21]:
#   Q15

# Create your own array of 7 daily study hours and calculate:

# Total hours
# Average hours
# Maximum hours
# Minimum hours

hours = np.array([6,5,6,3,0,5,6])
print(hours.sum())
print(hours.mean())
print(hours.max())
print(hours.min())

31
4.428571428571429
6
0


In [26]:
# Create a NumPy array containing numbers from 1 to 10.

# Expected Output:

# [1 2 3 4 5 6 7 8 9 10]Create a NumPy array containing numbers from 1 to 10.
arr  =  np.array([])
for i in range(1,11):
    arr = np.append(arr , i) 

print(arr)


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [28]:
# Create an array containing only zeros of size 5.

# Expected Output:

# [0. 0. 0. 0. 0.]

arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [30]:
# Create an array containing only ones of size 8.
arr = np.ones(8)
arr

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [33]:
# Create an array containing numbers from 10 to 100 with a step of 10.

# Expected Output:

# [10 20 30 40 50 60 70 80 90 100]

arr = np.array([])
for i in range(10 , 101 , 10):
    arr = np.append(arr , i)
arr

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [41]:
# Create an array containing 5 evenly spaced values between 0 and 1.
arr = np.linspace(0,1,5)
arr

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [43]:

arr = np.array([10,20,30,40,50])

# Add 25 to every element.
arr + 25

array([35, 45, 55, 65, 75])

In [44]:
arr = np.array([5,10,15,20])

# Multiply every element by 4.
arr * 4

array([20, 40, 60, 80])

In [45]:
arr = np.array([100,200,300,400])

# Divide every element by 10.
arr / 10

array([10., 20., 30., 40.])

In [46]:
arr = np.array([1,2,3,4,5])

# Square each element. 
arr ** 2

array([ 1,  4,  9, 16, 25])

In [47]:
arr = np.array([2,4,6,8])

# Cube each element.
arr ** 3

array([  8,  64, 216, 512])

In [48]:
marks = np.array([75,82,90,67,88,95])

# Find:

# Mean
# Sum
# Maximum
# Minimum

print(marks.mean())
print(marks.sum())
print(marks.max())
print(marks.min())

82.83333333333333
497
95
67


In [49]:
sales = np.array([1200,1500,1800,2000,1700])

# Find:

# Total Sales
# Average Sales

print(sales.sum())
print(sales.mean())

8200
1640.0


In [54]:
salary = np.array([25000,30000,45000,40000,50000])

# Find:

# Highest salary
# Lowest salary
# Average salary

print(salary.max())
print(salary.min())
print(salary.mean())

50000
25000
38000.0


In [55]:
# Create your own monthly expenses array and calculate:

# Total expense
# Average expense
# Maximum expense

expenses = np.array([100,150,200,300])
print(expenses.sum())
print(expenses.mean())
print(expenses.max())

750
187.5
300


In [58]:
# Q16
arr = np.array([10,20,30,40,50,60])

# Print:

# First element
# Last element

print(arr[-1])
print(arr[0])

60
10


In [60]:
# Print:

arr = np.array([20,30,40])

# using slicing.
arr[::]

array([20, 30, 40])

In [61]:
arr = np.array([20,30,40,50,60,70,80])
# Print the first 4 elements.
print(arr[0:4])

[20 30 40 50]


In [62]:
# Print the last 3 elements.
print(arr[-1:-4:-1])

[80 70 60]


In [63]:
# Print every second element.
print(arr[::2])

[20 40 60 80]


In [65]:
# Student Marks Analysis
marks = np.array([78,85,90,67,88,92,75])

# Find:

# Average marks
# Highest marks
# Lowest marks
# Total marks

print(marks.mean())
print(marks.max())
print(marks.min())
print(marks.sum())

82.14285714285714
92
67
575


In [66]:
# Daily Website Visitors
visitors = np.array([120,150,180,200,175,160,190])

# Find:

# Total visitors
# Average visitors
# Highest visitors day

print(visitors.sum())
print(visitors.mean())
print(visitors.max())

1175
167.85714285714286
200


In [67]:
# Company Revenue
revenue = np.array([50000,60000,55000,70000,65000])

# Find:

# Total revenue
# Average revenue
# Revenue range
print(revenue.sum())
print(revenue.mean())
print(revenue.min() ,"-", revenue.max() )

300000
60000.0
50000 - 70000


In [68]:
# Fitness Tracker
steps = np.array([5000,7000,8000,6000,9000,10000,7500])

# Find:

# Total steps
# Average steps
# Maximum steps
print(steps.sum())
print(steps.mean())
print(steps.max())

52500
7500.0
10000


In [74]:
# Study Hours Analysis
hours = np.array([2,3,4,5,3,6,4])

# Find:

# Total study hours
# Average study hours
print(hours.sum())
print(hours.mean())

27
3.857142857142857


In [75]:
expenses = np.array([1200,500,800,300,700,1000,400])

# Display:

# Total Expense
# Average Expense
# Highest Expense
# Lowest Expense
print(expenses.sum())
print(expenses.mean())
print(expenses.max())
print(expenses.min())

4900
700.0
1200
300


In [76]:
# Student Result Analyzer

# Input:

marks = np.array([78,85,90,67,88])

# Output:

# Average Marks
# Highest Marks
# Lowest Marks
# Total Marks

print(marks.mean())
print(marks.max())
print(marks.min())
print(marks.sum())

81.6
90
67
408


In [77]:
# Weekly Productivity Tracker

# Create an array of your study hours for 7 days.

# Display:

# Total Hours
# Average Hours
# Highest Hours
# Lowest Hours

hours = np.array([3,4,5,2,5,7,4])

print(hours.sum())
print(hours.mean())
print(hours.max())
print(hours.min())

30
4.285714285714286
7
2
