In [18]:
from sklearn.datasets import load_breast_cancer
import pandas as pd
import numpy as np
import math
data = load_breast_cancer()

X = data.data
y  = data.target

In [17]:
print(X.shape)
print(y.shape)
print(data.feature_names)
print(data.target_names)
print(len(data.feature_names))
classes , counts = np.unique(y , return_counts = True)
print(classes)
print('Malignant',counts[0])
print('Benign',counts[1])

(569, 30)
(569,)
['mean radius' 'mean texture' 'mean perimeter' 'mean area'
 'mean smoothness' 'mean compactness' 'mean concavity'
 'mean concave points' 'mean symmetry' 'mean fractal dimension'
 'radius error' 'texture error' 'perimeter error' 'area error'
 'smoothness error' 'compactness error' 'concavity error'
 'concave points error' 'symmetry error' 'fractal dimension error'
 'worst radius' 'worst texture' 'worst perimeter' 'worst area'
 'worst smoothness' 'worst compactness' 'worst concavity'
 'worst concave points' 'worst symmetry' 'worst fractal dimension']
['malignant' 'benign']
30
[0 1]
Malignant 212
Benign 357


In [19]:
z_values = [-5,-2,0,2,5]
for z in z_values:
    sigmoid = 1/(1+math.exp(-z))
    print(sigmoid)

0.0066928509242848554
0.11920292202211755
0.5
0.8807970779778823
0.9933071490757153


In [21]:
probabilities = [0.2, 0.5, 0.8]
for p in probabilities:
    odds = [p / (1 - p)]
    print(f"Probability: {p}, Odds: {odds}")

Probability: 0.2, Odds: [0.25]
Probability: 0.5, Odds: [1.0]
Probability: 0.8, Odds: [4.000000000000001]


In [22]:
probabilities = [0.15, 0.32, 0.49, 0.51, 0.82]
predicts = []
for i in probabilities:
    if i > 0.50:
        predicts.append(1)
    else:
        predicts.append(0)
print(predicts)

[0, 0, 0, 1, 1]


In [24]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
X_train , X_test,y_train , y_test = train_test_split(X , y , test_size = 0.2 , random_state = 42)
model = LogisticRegression(max_iter = 10000)

In [29]:
model.fit(X_train , y_train)
y_pred = model.predict(X_test)
print(y_pred[:10])
print(y_test[:10])


[1 0 0 1 1 0 0 0 1 1]
[1 0 0 1 1 0 0 0 1 1]


In [30]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test , y_pred)
print(accuracy)

0.956140350877193


In [31]:
from sklearn.metrics import confusion_matrix
confusion = confusion_matrix(y_test , y_pred)
print(confusion)

[[39  4]
 [ 1 70]]


In [33]:
from sklearn.metrics import precision_score , recall_score , f1_score
precision = precision_score(y_test , y_pred)
recall = recall_score(y_test , y_pred)
f1 = f1_score(y_test , y_pred)
print(precision)
print(recall)
print(f1)

0.9459459459459459
0.9859154929577465
0.9655172413793104
